const loggerobj = require('./logger')
const helperobj = require('./util/helper')
const formatterobj = require('../validator/formatter')
const obj = require('lodash')

loggerobj.logMessage('module system')
loggerobj.printWelcomeMessage()
console.log(loggerobj.loggerEndpoint)
console.log('-----------------------------------')
helperobj.getDate()
helperobj.getMonth()
helperobj.getbatchInfo()
console.log('-----------------------------------')
 formatterobj.trimInput()  
 formatterobj.changeToLowercase() 
 formatterobj.changeToUpperCase() 
 console.log('-----------------------------------')
 console.log(obj.chunk(["January", "February", "March", "April", "June","July","August", "September", "October", "November", " December"], 3))
 console.log(obj.tail([1, 3, 7, 9, 11, 13, 15, 17, 19]))
 console.log(obj.union([1,2,3], [3,4,5],[6,7,8]))
 console.log(obj.fromPairs([["horror","The Shining"],["drama","Titanic"],["thriller","Shutter Island"],["fantasy","Pans Labyrinth"]]))

